services:
    sql1:
        image: mcr.microsoft.com/mssql/server:2022-latest
        environment:
            ACCEPT_EULA: "Y"
            MSSQL_SA_PASSWORD: "test@123"
        ports:
            - "1433:1433"
        container_name: sql1
        hostname: sql1

    redis:
        image: redis:latest
        ports:
            - "6379:6379"
        container_name: redis
        hostname: redis